### ISSUE TITLE
UI Bug when I want to disable "Automatically stake new maturity"

### ISSUE THREAD

**Issue by HunterXuan** [iclighthouse/ICDexUI#2]
I have enable "Automatically stake new maturity" first, and when I wanna disable this option, the prompt window still says "Are you sure that you would like to automatically stake new maturity of this neuron?" which is somewhat confusing.

<img width="532" alt="image" src="https://github.com/iclighthouse/ICDexUI/assets/4209116/646c7ae0-72c4-4016-b3a9-606a7c41b67f">

**Comment by william-iclight** [comment]
We have fixed it. Please try again
